[package]
name = "vpm"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.81"
indicatif = "0.17.8"
octocrab = "0.39.0"
reqwest = "0.12.5"
serde = "1.0.204"
serde_json = "1.0.122"
thiserror = "1.0.63"
tokio = { version = "1.32.0", features = ["rt-multi-thread", "macros"] }
