[package]
name = "vpm"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.81"
indicatif = "0.17.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
tokio = { version = "1", features = ["fs", "io-std", "io-util", "macros", "rt-multi-thread"] }
uuid = { version = "1.7.0", features = ["v4", "fast-rng", "serde"] }
elasticsearch = "8.5.0-alpha.1"
async-openai = "0.18.3"
reqwest = { version = "0.11", default-features = false, features = ["json", "rustls-tls"] }
dotenv = "0.15.0"
walkdir = "2.4.0"
