[package]
name = "vpm"
version = "0.1.0"
edition = "2021"
license = "MIT"
copyright = "Copyright (c) 2024 Instachip"
authors = ["Instachip <team@getinstachip.com>"]

[dependencies]
clap = { version = "4.5.13", features = ["derive"] }
anyhow = "1.0.86"
semver = "1.0.23"
serde = { version = "1.0.205", features = ["derive"] }
async-openai = "0.18.3"
reqwest = { version = "0.11", default-features = false, features = ["json", "rustls-tls"] }
dotenv = "0.15.0"
walkdir = "2.4.0"
tokio = { version = "1", features = ["full"] }
chatgpt_rs = "1.2.3"