name: Publish Install Script

on:
  push:
    branches:
      - main  # or your default branch
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Make install.sh executable
      run: chmod +x install.sh

    - name: Upload install.sh as an artifact
      uses: actions/upload-artifact@v3
      with:
        name: install-script
        path: install.sh

    - name: Create GitHub Release
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v1
      with:
        files: install.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
