name: Publish Install Script and Release

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for all tags and branches

    - name: Get latest tag and increment version
      id: get_version
      run: |
        git fetch --tags
        LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
        LATEST_VERSION=${LATEST_TAG#v}
        IFS='.' read -ra VERSION_PARTS <<< "$LATEST_VERSION"
        MAJOR=${VERSION_PARTS[0]}
        MINOR=${VERSION_PARTS[1]}
        PATCH=$((VERSION_PARTS[2] + 1))
        NEW_VERSION="$MAJOR.$MINOR.$PATCH"
        echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
        echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT

    - name: Make install.sh executable
      run: chmod +x install.sh

    - name: Upload install.sh as an artifact
      uses: actions/upload-artifact@v3
      with:
        name: install-script
        path: install.sh

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.get_version.outputs.new_version }}
        release_name: Release v${{ steps.get_version.outputs.new_version }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./install.sh
        asset_name: install.sh
        asset_content_type: text/x-shellscript

    - name: Update version in Cargo.toml
      run: |
        sed -i 's/^version = ".*"/version = "${{ env.NEW_VERSION }}"/' Cargo.toml

    - name: Commit and push changes
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add Cargo.toml
        git commit -m "Bump version to ${{ env.NEW_VERSION }}"
        git push

    - name: Push new tag
      run: |
        git push origin v${{ env.NEW_VERSION }}
